services:
  - type: web
    name: course-project-api
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn course_project.wsgi:application --bind 0.0.0.0:10000"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: courses-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"

databases:
  - name: courses-db
    plan: free
    databaseName: courses
    user: postgres